### ISSUE TITLE
Release 0.1.1.0

### ISSUE THREAD

**Issue by phadej** [necrobious/uuid-aeson#5]
Thanks!

**Comment by mjhoy** [comment]
Just curious, will this be released? Running into dependency constraint issues with 0.1.0.0.

**Comment by mjhoy** [comment]
Ah. Maybe this is now incorporated in Data.Aeson? Looks like that has UUID instances.

**Comment by phadej** [comment]
`aeson` has `UUID` instances, so the release isn't necessary indeed.
